name: assignment3
on:
  push:
jobs:

  build:
      runs-on: ubuntu-latest
      steps:
      - name: Set DATE
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create log.txt file
        run: touch log.txt
      - name: Insert date and names to log.txt
        run: |
          echo ${{ env.DATE }} >> log.txt
          echo "Itay Finkelshtein, Dolev Ifrah" >> log.txt
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: meals-service:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Check successful image creation and write to log file
        if: success()
        run: echo "image successfully built" >> log.txt

      - name: Check failed image creation and write to log file
        if: failure()
        run: echo "image not able to be built" >> log.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meals-service
          path: /tmp/image.tar

      - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: log-file
            path: /log.txt

